name: CI
on: push
jobs:
  myjob:
    runs-on: ubuntu-20.04
    steps:
      - name: NoName
        run: echo "hello world"
  test:
    needs: [myjob]
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install
        run: npm install semantic-release-github
  
  release:
    needs: [test]
    runs-on: ubuntu-20.04
    steps:
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run semantic-release-github
