name: CI
on: push
jobs:
  release:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Semver Release Manager
      - uses: home-furnishing-nordic/semver-release-manager@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
